/* Generated By:JavaCC: Do not edit this line. lexerConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MODIFICADOR = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int TIPODATO = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int ELSEIF = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int PARENTESISIZQUIERDO = 12;
  /** RegularExpression Id. */
  int PARENTESISDERECHO = 13;
  /** RegularExpression Id. */
  int LLAVEIZQUIERDA = 14;
  /** RegularExpression Id. */
  int LLAVEDERECHA = 15;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 16;
  /** RegularExpression Id. */
  int COMILLASDOBLES = 17;
  /** RegularExpression Id. */
  int ASIGNACION = 18;
  /** RegularExpression Id. */
  int EXPRESION = 19;
  /** RegularExpression Id. */
  int MAS = 20;
  /** RegularExpression Id. */
  int MENOS = 21;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 22;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 23;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 24;
  /** RegularExpression Id. */
  int STRING_LITERAL = 25;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MODIFICADOR>",
    "\"class\"",
    "<TIPODATO>",
    "\"if\"",
    "\"else\"",
    "\"else if\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\"\"",
    "\"=\"",
    "<EXPRESION>",
    "\"+\"",
    "\"-\"",
    "<INTEGER_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFICADOR>",
  };

}
